################################################################################
bitly:
  restart: always
  image: ${IMAGE_NAME}
  environment:
    MICRO_REGISTRY: mdns
    MICRO_SERVER_NAME: denkhaus.micro.srv.bitly
    BITLY_ACCESS_TOKEN: ${BITLY_ACCESS_TOKEN}
    BITLY_SECRET: ${BITLY_SECRET}
  labels:
    io.rancher.container.pull_image: always
    # io.rancher.scheduler.affinity:host_label: name=metis
    # io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
  