#!/bin/bash

VERSION_CUR=$(git describe --abbrev=0 --tags) 
echo "current version is $VERSION_CUR" 
VERSION_NEW=$(echo $VERSION_CUR | awk 'BEGIN { FS="." } { $3++; if ($3 > 99) { $3=0; $2++; if ($2 > 99) { $2=0; $1++ } } } { printf "%d.%d.%d", $1, $2, $3 }') 
echo "new version is $VERSION_NEW" 

git add -A  
test $(git status --porcelain 2>/dev/null | egrep "^(M| M)" | wc -l) == 0 || git commit -a -m $VERSION_NEW && \
git tag $VERSION_NEW && git push origin master
 